<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $moduleLabel }} — Record #{{ $recordId }}</title>
    <style nonce="{{ request()->attributes->get('csp_nonce') }}">
        * { box-sizing: border-box; }
        body {
            font-family: 'Geist', sans-serif;
            font-size: 11pt;
            color: #1e293b;
            margin: 24px;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 3px solid #0b4aa2;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }
        .header .brand { font-size: 18pt; font-weight: bold; color: #0b4aa2; }
        .header .sub { font-size: 9pt; color: #64748b; }
        h1 { font-size: 14pt; color: #0f172a; }
        table.details {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }
        table.details th, table.details td {
            border: 1px solid #cbd5e1;
            padding: 8px 10px;
            text-align: left;
            vertical-align: top;
        }
        table.details th {
            background: #eef2f7;
            width: 30%;
            font-weight: bold;
        }
        .footer {
            margin-top: 32px;
            border-top: 1px solid #cbd5e1;
            padding-top: 8px;
            font-size: 8pt;
            color: #64748b;
        }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="brand">PGS</div>
            <div class="sub">Performance Governance System — TRC DOH</div>
        </div>
        <div class="sub">Generated {{ date('Y-m-d H:i') }} by {{ $generatedBy }}</div>
    </div>

    <h1>{{ $moduleLabel }} — Record #{{ $recordId }}</h1>

    <table class="details">
        @if ($title !== '')
            <tr><th>Title</th><td>{{ $title }}</td></tr>
        @endif
        @if ($description !== '')
            <tr><th>Description</th><td>{{ $description }}</td></tr>
        @endif
        @if ($originalName !== '')
            <tr><th>File</th><td>{{ $originalName }}</td></tr>
        @endif
        @if ($fileSize !== '')
            <tr><th>Size</th><td>{{ $fileSize }}</td></tr>
        @endif
        @if ($mimeType !== '')
            <tr><th>Type</th><td>{{ $mimeType }}</td></tr>
        @endif
        @if ($status !== '')
            <tr><th>Status</th><td>{{ $status }}</td></tr>
        @endif
        @if ($uploadedAt !== '')
            <tr><th>Uploaded</th><td>{{ $uploadedAt }}</td></tr>
        @endif
        @foreach (($extraRows ?? []) as $row)
            @if (($row[1] ?? '') !== '')
                <tr><th>{{ $row[0] }}</th><td>{{ $row[1] }}</td></tr>
            @endif
        @endforeach
        <tr><th>Record ID</th><td>{{ $recordId }}</td></tr>
    </table>

    <div class="footer">
        This document was generated by the PGS system. Data shown reflects the system record at generation time.
    </div>
</body>
</html>
