<?php

return [
  'collab' => [
    'title' => 'Collaborative Healthcare Management',
    'description' => 'Provide community therapy combined with multi-disciplinary approach expanded to other forms of substance use, abuse, and addiction within the local health care provider network.',
    'image' => '1.png',
    'table' => 'collab',
    'progress_table' => 'collab_progress',
    'roadmaps' => ['roadmap_relapse_rate.php', 'roadmap_quality_of_life.php'],
    'roles' => ['admin', 'employee', 'focal'],
  ],
  'research' => [
    'title' => 'Research',
    'description' => 'Generate new knowledge and evidence-based practices that enhance the quality and effectiveness of treatment and rehabilitation services for substance use disorders.',
    'image' => '3.png',
    'table' => 'research',
    'progress_table' => 'research_progress',
    'roadmaps' => ['roadmap_employee_engagement.php', 'roadmap_outputs.php'],
    'roles' => ['admin', 'employee', 'focal'],
  ],
  'training' => [
    'title' => 'Training',
    'description' => 'Develop competencies of personnel through continuous learning and skills enhancement programs to ensure delivery of quality services.',
    'image' => '5.png',
    'table' => 'training',
    'progress_table' => 'training_progress',
    'roadmaps' => ['roadmap_certified_tot.php', 'roadmap_percentage_trained.php'],
    'roles' => ['admin', 'employee', 'focal'],
  ],
  'culture' => [
    'title' => 'Culture of Organization',
    'description' => 'Strengthen organizational culture anchored on shared values, teamwork, and continuous improvement to achieve strategic objectives.',
    'image' => '2.png',
    'table' => 'culture',
    'progress_table' => 'culture_progress',
    'roadmaps' => ['roadmap_employee_engagement.php', 'roadmap_client_satisfaction.php'],
    'roles' => ['admin', 'employee', 'focal'],
  ],
  'resilience' => [
    'title' => 'Resilience',
    'description' => 'Build organizational capacity to anticipate, respond to, and adapt to changes and challenges in the healthcare environment.',
    'image' => '4.png',
    'table' => 'resilience',
    'progress_table' => 'resilience_progress',
    'roadmaps' => ['roadmap_green_viability.php', 'roadmap_reduced_adverse_events.php'],
    'roles' => ['admin', 'employee', 'focal'],
  ],
  'technology' => [
    'title' => 'Technology',
    'description' => 'Leverage technology and digital solutions to improve service delivery, operational efficiency, and patient outcomes.',
    'image' => '6.png',
    'table' => 'technology',
    'progress_table' => 'technology_progress',
    'roadmaps' => ['roadmap_employee_records_turnaround.php', 'roadmap_patient_records_turnaround.php'],
    'roles' => ['admin', 'employee', 'focal'],
  ],
  'revenue' => [
    'title' => 'Revenue',
    'description' => 'Optimize revenue generation and resource mobilization to support organizational sustainability and strategic initiatives.',
    'image' => '7.png',
    'table' => 'revenue',
    'progress_table' => 'revenue_progress',
    'roadmaps' => ['roadmap_hospital_income.php', 'roadmap_non_traditional_revenue.php'],
    'roles' => ['admin', 'employee', 'focal'],
  ],
];
